import 'package:get/get_navigation/src/root/internacionalization.dart';

class Languages extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        'en_US': {
          'appTitle': 'Multi Role App',
          'scannedBarcode': 'Scan QR Code',
          'nothing': 'Nothing!',
          "webViewTitle": "WebView",
          'copy': 'Copy',
          'redirect': 'Redirect',
          'copiedToClipboard': 'Copied to clipboard!',
          'pleaseEnterText': 'Please enter some text!',
          'rewardedAdNotLoaded': 'Rewarded ad is not loaded yet. Please try again.',
          'qrCodeGenerator': 'QR Code Generator',
          'generateQRCode': 'Generate QR Code',
          'scannerOverlayTitle': 'Scanner with Overlay Example',
          'error': 'Error',
          'cameraError': 'Camera not available',
          'toggleFlashlight': 'Toggle Flashlight',
          'switchCamera': 'Switch Camera',
          'videoPlayerTitle': 'Video Player',
          'audioPlayerTitle': 'Audio Player',
          'play': 'Play',
          'pause': 'Pause',
          'stop': 'Stop',
          'next': 'Next',
          'previous': 'Previous',
          'backward10s': 'Backward 10s',
          'forward10s': 'Forward 10s',
          'trackTitle': 'Title: ',
          'trackArtist': 'Artist: ',
          'trackReleaseDate': 'Release Date: ',
          'position': 'Position: ',
          'scanning': 'Scanning...',
          'noPicturesFound': 'No pictures found',
          'applyFilter': 'Apply Filter',
          'chooseFilter': 'Choose a filter to apply to this image.',
          'cancel': 'Cancel',
          'filterPreview': 'Filter Preview',
          'save': 'Save',
          'saveToGallery': 'Save to Gallery', 
          'fullScreenViewer': 'Full Screen Viewer',
          'close': 'Close',
          'loadingImage': 'Loading image...',
          'documentScanner': 'Document Scanner',
          'delete': 'Delete',
        },
        'ur_PK': {
          'appTitle': 'ملٹی رول ایپ',
          'scannedBarcode': 'QR کوڈ اسکین کریں',
          'nothing': 'کچھ نہیں!',
          "webViewTitle": "ویب ویو",
          'copy': 'نقل کریں',
          'redirect': 'منتقل کریں',
          'copiedToClipboard': 'کاپی کر دیا گیا!',
          'pleaseEnterText': 'براہ کرم کچھ متن درج کریں!',
          'rewardedAdNotLoaded': 'انعامی اشتہار ابھی لوڈ نہیں ہوا۔ براہ کرم دوبارہ کوشش کریں۔',
          'qrCodeGenerator': 'QR کوڈ جنریٹر',
          'generateQRCode': 'QR کوڈ بنائیں',
          'scannerOverlayTitle': 'مثال کے ساتھ اسکینر',
          'error': 'خرابی',
          'cameraError': 'کیمرہ دستیاب نہیں',
          'toggleFlashlight': 'فلیش لائٹ آن کریں',
          'switchCamera': 'کیمرہ تبدیل کریں',
          'videoPlayerTitle': 'ویڈیو پلیئر',
          'audioPlayerTitle': 'آڈیو پلیئر',
          'play': 'پلے',
          'pause': 'پوز',
          'stop': 'روکیں',
          'next': 'اگلا',
          'previous': 'پچھلا',
          'backward10s': 'پیچھے 10 سیکنڈ',
          'forward10s': 'آگے 10 سیکنڈ',
          'trackTitle': 'عنوان: ',
          'trackArtist': 'فنکار: ',
          'trackReleaseDate': 'ریلیز کی تاریخ: ',
          'position': 'پوزیشن: ',
          'scanning': 'اسکیننگ...',
          'noPicturesFound': 'کوئی تصاویر نہیں ملیں',
          'applyFilter': 'فلٹر لگائیں',
          'chooseFilter': 'اس تصویر پر لاگو کرنے کے لئے فلٹر منتخب کریں۔',
          'cancel': 'منسوخ کریں',
          'filterPreview': 'فلٹر کا پیش نظارہ',
          'save': 'محفوظ کریں',
          'saveToGallery': 'گیلری میں محفوظ کریں', // Added here
          'fullScreenViewer': 'پوری اسکرین دیکھنے والا',
          'close': 'بند کریں',
          'loadingImage': 'تصویر لوڈ ہو رہی ہے...',
          'documentScanner': 'دستاویز سکینر',
          'delete': 'حذف کریں',
        },
        'ar': {
          'appTitle': 'تطبيق الأدوار المتعددة',
          'scannedBarcode': 'QR كود الممسوح',
          'nothing': 'لا شيء!',
          "webViewTitle": "عرض الويب",
          'copy': 'نسخ',
          'redirect': 'تحويل',
          'copiedToClipboard': 'تم النسخ إلى الحافظة!',
          'pleaseEnterText': 'يرجى إدخال بعض النصوص!',
          'rewardedAdNotLoaded': 'الإعلان المدعوم لم يتم تحميله بعد. يرجى المحاولة مرة أخرى.',
          'qrCodeGenerator': 'مولد QR كود',
          'generateQRCode': 'إنشاء QR كود',
          'scannerOverlayTitle': 'تطبيق المسح مع طبقة فوقية',
          'error': 'خطأ',
          'cameraError': 'الكاميرا غير متاحة',
          'toggleFlashlight': 'تبديل الفلاش',
          'switchCamera': 'تبديل الكاميرا',
          'videoPlayerTitle': 'مشغل الفيديو',
          'audioPlayerTitle': 'مشغل الصوت',
          'play': 'تشغيل',
          'pause': 'إيقاف مؤقت',
          'stop': 'توقف',
          'next': 'التالي',
          'previous': 'السابق',
          'backward10s': 'للخلف 10 ثوان',
          'forward10s': 'إلى الأمام 10 ثوان',
          'trackTitle': 'العنوان: ',
          'trackArtist': 'الفنان: ',
          'trackReleaseDate': 'تاريخ الإصدار:',
          'position': 'الموقع: ',
          'scanning': 'جارٍ المسح...',
          'noPicturesFound': 'لا توجد صور',
          'applyFilter': 'تطبيق الفلتر',
          'chooseFilter': 'اختر فلتر لتطبيقه على هذه الصورة.',
          'cancel': 'إلغاء',
          'filterPreview': 'معاينة الفلتر',
          'save': 'حفظ',
          'saveToGallery': 'حفظ إلى المعرض', 
          'fullScreenViewer': 'عارض الصورة بالكامل',
          'close': 'إغلاق',
          'loadingImage': 'جارٍ تحميل الصورة...',
          'documentScanner': 'ماسح الوثائق',
          'delete': 'حذف',
        },
        'es': {
          'appTitle': 'Aplicación de múltiples roles',
          'scannedBarcode': 'Escanear código QR',
          'nothing': '¡Nada!',
          "webViewTitle": "Vista web",
          'copy': 'Copiar',
          'redirect': 'Redirigir',
          'copiedToClipboard': '¡Copiado al portapapeles!',
          'pleaseEnterText': '¡Por favor, ingrese algún texto!',
          'rewardedAdNotLoaded': 'El anuncio recompensado no se ha cargado aún. Por favor, inténtelo de nuevo.',
          'qrCodeGenerator': 'Generador de QR Code',
          'generateQRCode': 'Generar QR Code',
          'scannerOverlayTitle': 'Escáner con superposición',
          'error': 'Error',
          'cameraError': 'Cámara no disponible',
          'toggleFlashlight': 'Activar linterna',
          'switchCamera': 'Cambiar cámara',
          'videoPlayerTitle': 'Reproductor de video',
          'audioPlayerTitle': 'Reproductor de audio',
          'play': 'Reproducir',
          'pause': 'Pausar',
          'stop': 'Detener',
          'next': 'Siguiente',
          'previous': 'Anterior',
          'backward10s': 'Atrás 10s',
          'forward10s': 'Adelante 10s',
          'trackTitle': 'Título: ',
          'trackArtist': 'Artista: ',
          'trackReleaseDate': 'Fecha de lanzamiento: ',
          'position': 'Posición: ',
          'scanning': 'Escaneando...',
          'noPicturesFound': 'No se encontraron imágenes',
          'applyFilter': 'Aplicar filtro',
          'chooseFilter': 'Elige un filtro para aplicar a esta imagen.',
          'cancel': 'Cancelar',
          'filterPreview': 'Vista previa del filtro',
          'save': 'Guardar',
          'saveToGallery': 'Guardar en la galería', 
          'fullScreenViewer': 'Visor de pantalla completa',
          'close': 'Cerrar',
          'loadingImage': 'Cargando imagen...',
          'documentScanner': 'Escáner de documentos',
          'delete': 'Eliminar',
        },
      };
}
