// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDVIMwGiPnPx6vShJp_dwWm8C96dzw_nQY',
    appId: '1:857914830179:web:3acce90c595448c0357756',
    messagingSenderId: '857914830179',
    projectId: 'multi-app-f0b1c',
    authDomain: 'multi-app-f0b1c.firebaseapp.com',
    storageBucket: 'multi-app-f0b1c.appspot.com',
    measurementId: 'G-W1F58BBFN7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdSdUFuwDXI_DTDWjGBeWHi_DCakvrGnQ',
    appId: '1:857914830179:android:e196f3dfd7880064357756',
    messagingSenderId: '857914830179',
    projectId: 'multi-app-f0b1c',
    storageBucket: 'multi-app-f0b1c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCb8ZGJORhcAcg4K-pZX1bVNgWYVJrPfbs',
    appId: '1:857914830179:ios:af6a703b6e99664c357756',
    messagingSenderId: '857914830179',
    projectId: 'multi-app-f0b1c',
    storageBucket: 'multi-app-f0b1c.appspot.com',
    iosBundleId: 'com.example.multiApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCb8ZGJORhcAcg4K-pZX1bVNgWYVJrPfbs',
    appId: '1:857914830179:ios:af6a703b6e99664c357756',
    messagingSenderId: '857914830179',
    projectId: 'multi-app-f0b1c',
    storageBucket: 'multi-app-f0b1c.appspot.com',
    iosBundleId: 'com.example.multiApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDVIMwGiPnPx6vShJp_dwWm8C96dzw_nQY',
    appId: '1:857914830179:web:cbc03e63eb71f26b357756',
    messagingSenderId: '857914830179',
    projectId: 'multi-app-f0b1c',
    authDomain: 'multi-app-f0b1c.firebaseapp.com',
    storageBucket: 'multi-app-f0b1c.appspot.com',
    measurementId: 'G-X173J8EMZE',
  );
}
